version: 2
jobs:
  build:
        machine:
         timezone:
          Asia/Tokyo

        dependencies:
         override:
           - sudo pip install awscli
         post:
           - aws configure set region ap-northeast-1

        deployment:
          production: # just a label; label names are completely up to you
          branch: master
          commands:
            - aws s3 sync _site s3://ytoku.net/ --delete
