version: 2
jobs:
  build:
        machine:
         timezone:
          Asia/Tokyo

        dependencies:
         override:
           - sudo pip install awscli
         post:
           - aws configure set region ap-northeast-1

        steps:
          - checkout
          - run:
              name: "deploy ytoku_net"
              branch: master
              command:
                - aws s3 sync _site s3://ytoku.net/ --delete

